owner: tsueri
repo: upptime

sites:
  - name: tsueri.cloud
    url: https://tsueri.cloud
    icon: https://raw.githubusercontent.com/tsueri/upptime/master/assets/cloud.png
  - name: Online Document Editor
    url: $URL_OFFICE
    headers:
    - "Authorization: Basic $AUTH_OFFICE"
    - "Content-Type: text/html"
    icon: https://raw.githubusercontent.com/tsueri/upptime/master/assets/paper.png
  - name: finkencloud
    url: https://cloud.wohnfink.ch
    icon: https://raw.githubusercontent.com/tsueri/upptime/master/assets/cloud.png
  - name: social.tsueri.cloud (Mastodon)
    url: https://social.tsueri.cloud/health
    icon: https://raw.githubusercontent.com/tsueri/upptime/master/assets/Mastodon_Logotype_(Simple).svg
    __dangerous__body_down_if_text_missing: 'OK'
  - name: Mailserver
    url: email.campa.tools
    icon: https://raw.githubusercontent.com/tsueri/upptime/master/assets/e-mail.png
    check: "tcp-ping"
    port: 25
  - name: Portal
    url: https://portal.campa.tools
  - name: bitwarden
    url: https://bitwarden.tsueri.cloud
    icon: https://raw.githubusercontent.com/tsueri/upptime/master/assets/bitwarden.svg
  - name: Webserver
    url: https://web2.campa.tools
    icon: https://raw.githubusercontent.com/tsueri/upptime/master/assets/globe.png
  - name: DNS 1
    check: "tcp-ping"
    url: $URL_DNS1
    port: 53
    icon: https://raw.githubusercontent.com/tsueri/upptime/master/assets/compass.png
status-website:
  cname: status.campa.tools
  logoUrl: https://raw.githubusercontent.com/tsueri/upptime/master/assets/logo-tsueri-grey.svg
  faviconSvg: https://raw.githubusercontent.com/tsueri/upptime/master/assets/logo-tsueri-grey.svg
  theme: night
  name: Statuspage by tsueri
  introTitle: "Check the status of all **campa.tools** services."
  introMessage: "Updates to unplanned downtime [can be found here](https://github.com/tsueri/upptime/issues)."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  css: "img.svelte-a08hsz { display: none; }"
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
user-agent: tsueri
