owner: tsueri
repo: upptime

sites:
  - name: tsueri.cloud
    url: https://tsueri.cloud
    icon: https://raw.githubusercontent.com/tsueri/upptime/master/assets/cloud.png
  - name: Online Document Editor
    url: $URL_OFFICE
    __dangerous__body_down: "false"
    icon: https://raw.githubusercontent.com/tsueri/upptime/master/assets/paper.png
  - name: Mailserver
    url: email.campa.tools
    icon: https://raw.githubusercontent.com/tsueri/upptime/master/assets/e-mail.png
    check: "tcp-ping"
    port: 25
  - name: Webserver
    url: https://web.campa.tools
    icon: https://raw.githubusercontent.com/tsueri/upptime/master/assets/globe.png
  - name: DNS 1
    check: "tcp-ping"
    port: 80
    url: $URL_DNS1
    icon: https://raw.githubusercontent.com/tsueri/upptime/master/assets/compass.png
  - name: DNS 2
    check: "tcp-ping"
    port: 80
    url: $URL_DNS2
    icon: https://raw.githubusercontent.com/tsueri/upptime/master/assets/compass.png
status-website:
  cname: status.campa.tools
  logoUrl: https://raw.githubusercontent.com/tsueri/upptime/master/assets/logo-tsueri-grey.svg
  faviconSvg: https://raw.githubusercontent.com/tsueri/upptime/master/assets/logo-tsueri-grey.svg
  theme: dark
  name: Statuspage by tsueri
  introTitle: "Check the status of all **campa.tools** Services."
  introMessage: "Updates to unplanned downtime [can be found here](https://github.com/tsueri/upptime/issues)."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  css: "img.svelte-a08hsz { display: none; }"
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
user-agent: tsueri
